version: '3.8'
services:
  api:
    build: .
    network_mode: "host"
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - LIGHTNING_NODE_API_URL=${LIGHTNING_NODE_API_URL}
    ports:
      - "3000:3000"
