version: '3.8'

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  api:
    build: .
    restart: always
    ports:
      - '3000:3000'
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DB_NAME=holdinvoices
      - DB_PORT=5432
    depends_on:
      - db

volumes:
  db:
    driver: local
