# .github/workflows/deploy-api.yml
name: Deploy API

on:
  push:
    branches: 
      - main
      - 'feature/**'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          echo "Starting deployment..."
          
          # Determine which branch to deploy
          DEPLOY_BRANCH="${{ github.event.inputs.branch || github.ref_name }}"
          echo "Deploying branch: $DEPLOY_BRANCH"
          
          # Stop the API service
          systemctl stop civkit-api.service
          
          cd /root/civkit-api
          
          # Fetch all branches and tags
          git fetch --all --prune --tags --force
          
          # Save current changes
          git stash
          
          # Force clean state
          git reset --hard HEAD
          git clean -fd
          
          # Checkout and update the specified branch
          git checkout $DEPLOY_BRANCH
          git reset --hard origin/$DEPLOY_BRANCH
          git pull origin $DEPLOY_BRANCH --force
          
          # Clear caches but preserve node_modules
          rm -rf dist tsconfig.tsbuildinfo
          
          # Proper build check
          npm install
          npm run build
          if [ $? -ne 0 ]; then
              echo "Build failed! Not starting service."
              exit 1
          fi
          
          systemctl start civkit-api.service
          
          echo "API Deployment completed!"
