# .github/workflows/deploy-api.yml
name: Deploy API

on:
  push:
    branches: 
      - main
      - 'feature/**'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          echo "Starting API deployment..."
          
          # Stop both services
          systemctl stop frontend.service
          systemctl stop civkit-api.service
          
          cd /root/civkit-api
          
          # Fetch all branches and tags
          git fetch --all --prune --tags --force
          
          # Save current changes
          git stash
          
          # Force clean state
          git reset --hard HEAD
          git clean -fd
          
          # Checkout and update main first
          git checkout main
          git reset --hard origin/main
          git pull origin main --force
          
          # If deploying feature branch
          if [ "${{ github.ref_name }}" != "main" ]; then
            echo "Deploying feature branch: ${{ github.ref_name }}"
            git fetch origin ${GITHUB_REF#refs/heads/}:${GITHUB_REF#refs/heads/} --force
            git checkout ${{ github.ref_name }}
            git reset --hard origin/${{ github.ref_name }}
          fi
          
          # Clear caches but preserve node_modules
          rm -rf dist tsconfig.tsbuildinfo
          
          npm install
          npm run build || echo "Build had issues but continuing..."
          
          # Start API first
          systemctl start civkit-api.service
          sleep 5  # Give API time to fully start
          
          # Then start frontend
          systemctl start frontend.service
          
          # Log status of both services
          echo "Service statuses:"
          systemctl status civkit-api.service --no-pager
          systemctl status frontend.service --no-pager
          
          echo "API Deployment completed!"
