name: Deploy API

on:
  push:
    branches: 
      - main
      - 'feature/**'
  workflow_dispatch:  # This enables manual runs
    inputs:
      branch:
        description: 'Branch to deploy'
        type: string
        required: true
        default: 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          echo "Starting deployment..."
          systemctl stop civkit-api.service
          cd /root/civkit-api
          git fetch origin
          git checkout ${{ github.event.inputs.branch || github.ref_name }}
          git pull origin ${{ github.event.inputs.branch || github.ref_name }}
          npm install
          npm run build
          systemctl start civkit-api.service
